on: workflow_dispatch
name: Update prod branch on release
jobs:
  createafile:
    name: creating a file for upload
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    
    - uses: actions/upload-artifact@v2
      with:
        name: world
        path: world.txt
        
        
  updateBranch:
    name: Update staging branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: staging
        
    - run: echo hello > world.txt
        
    
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        commit_message: Committing a change
