on: workflow_dispatch
name: Update prod branch on release
jobs:
  updateBranch:
    name: Update staging branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: staging
        
        
    - uses: actions/upload-artifact@v2
      with:
        name: readme-file
        path: README.txt
    
    #this is where I would change the file. IE Download the artifact
    - name: delete the readme
      run: git rm README.txt
    
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        commit_message: Committing a change
