on: pull_request
name: Update prod branch on release
jobs:
  updateBranch:
    name: Update staging branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: staging
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: tell them who you are
      run: |
        git config --global user.email "68mschmitt@gmail.com"
        git config --global user.name "Mike Schmitt"
    
    #this is where I would change the file
    - name: delete the readme
      run: git rm README.txt
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: check for changes
      run: git status
    - name: commit changed files
      run: git commit -m "Auto updating README.txt"
    - name: push code to master
      run: git push -u origin develop
