on: pull_request
name: Update prod branch on release
jobs:
  updateBranch:
    name: Update staging branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: staging
    
    #this is where I would change the file
    - shell: bash
      run: |
        value=`cat README.txt`
        expr $value + "itworks" > math-homework.txt

    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating README.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:staging
